package gov.osha.dteAdmin;

// Generated Nov 21, 2012 11:24:52 AM by Hibernate Tools 4.0.0

import javax.persistence.*;

/**
 * BatchLoadErrors generated by hbm2java
 */
@Entity
@Table(name = "BATCH_LOAD_ERRORS", schema = "DTE_COURSE_ADMIN")
public class BatchLoadErrors implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5887900792460426384L;
	private BatchLoadErrorsId id;

	public BatchLoadErrors() {
	}

	public BatchLoadErrors(BatchLoadErrorsId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "title", column = @Column(name = "TITLE", length = 250)),
			@AttributeOverride(name = "edCenter", column = @Column(name = "ED_CENTER", length = 100)),
			@AttributeOverride(name = "state", column = @Column(name = "STATE", length = 30)),
			@AttributeOverride(name = "location", column = @Column(name = "LOCATION", length = 100)),
			@AttributeOverride(name = "address", column = @Column(name = "ADDRESS", length = 100)),
			@AttributeOverride(name = "errorMessage", column = @Column(name = "ERROR_MESSAGE", length = 2000)) })
	public BatchLoadErrorsId getId() {
		return this.id;
	}

	public void setId(BatchLoadErrorsId id) {
		this.id = id;
	}

}
