package gov.osha.dteAdmin;

// Generated Nov 21, 2012 11:24:52 AM by Hibernate Tools 4.0.0

import javax.persistence.*;
import javax.xml.bind.annotation.XmlRootElement;
import java.math.BigDecimal;

/**
 * CourseLanguage generated by hbm2java
 */
@Entity
@Table(name = "OTI_COURSE_LANGUAGES", schema = "DTE_COURSE_ADMIN")
@XmlRootElement
public class CourseLanguage implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = -7310448254230502056L;
    private BigDecimal id;
    private String lang;
    private String description;
    private String updateUser;

    public CourseLanguage() {
    }

    public CourseLanguage(BigDecimal id, String lang, String description, String updateUser) {
        setId(id);
        setLang(lang);
        setDescription(description);
        setUpdateUser(updateUser);
    }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "G1")
    @SequenceGenerator(name = "G1", sequenceName = "oti_course_lang_seq", allocationSize = 1)
    @Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
    public BigDecimal getId() {
        return this.id;
    }

    public void setId(BigDecimal id) {
        this.id = id;
    }

    @Column(name = "LANG", nullable = false, length = 30)
    public String getLang() {
        return this.lang;
    }

    public void setLang(String lang) {
        this.lang = lang;
    }

    @Column(name = "DESCRIPTION", length = 250)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "UPDATE_USER", length = 30)
    public String getUpdateUser() {
        return this.updateUser;
    }

    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

}
