package gov.osha.dteAdmin;

// Generated Nov 21, 2012 11:24:52 AM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * CourseLanguage generated by hbm2java
 */
@Entity
@Table(name = "OTI_COURSE_LANGUAGES", schema = "DTE_COURSE_ADMIN")
@XmlRootElement
public class CourseLanguage implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7310448254230502056L;
	private BigDecimal id;
	private String lang;
	private String description;

	public CourseLanguage() {
	}

	public CourseLanguage(BigDecimal id, String lang, String description) {
		this.id = id;
		this.lang = lang;
		this.description = description;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "LANG", nullable = false, length = 30)
	public String getLang() {
		return this.lang;
	}

	public void setLang(String lang) {
		this.lang = lang;
	}

	@Column(name = "DESCRIPTION", length = 250)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
