package gov.osha.dteAdmin;

// Generated Nov 21, 2012 11:24:52 AM by Hibernate Tools 4.0.0

import javax.persistence.*;
import javax.xml.bind.annotation.XmlRootElement;
import java.math.BigDecimal;

/**
 * CourseTitle generated by hbm2java
 */
@Entity
@Table(name = "OTI_COURSE_TITLES", schema = "DTE_COURSE_ADMIN")
@XmlRootElement
public class CourseTitle implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 4264423995812179121L;
    private BigDecimal id;
    private String name;
    private String description;
    private String descUrl;
    private String updateUser;

    public CourseTitle() {
    }

    public CourseTitle(BigDecimal id, String name, String description,
                       String descUrl, String updateUser) {
        setId(id);
        setName(name);
        setDescription(description);
        setDescUrl(descUrl);
        setUpdateUser(updateUser);
    }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "G1")
    @SequenceGenerator(name = "G1", sequenceName = "oti_course_title_seq", allocationSize = 1)
    @Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
    public BigDecimal getId() {
        return this.id;
    }

    public void setId(BigDecimal id) {
        this.id = id;
    }

    @Column(name = "NAME", nullable = false, length = 250)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "DESCRIPTION", length = 4000)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "DESC_URL", length = 100)
    public String getDescUrl() {
        return this.descUrl;
    }

    public void setDescUrl(String descUrl) {
        this.descUrl = descUrl;
    }

    @Column(name = "UPDATE_USER", length = 30)
    public String getUpdateUser() {
        return this.updateUser;
    }

    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

}
