package gov.osha.dteAdmin;

// Generated Nov 21, 2012 11:24:52 AM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * CourseTitle generated by hbm2java
 */
@Entity
@Table(name = "OTI_COURSE_TITLES", schema = "DTE_COURSE_ADMIN")
@XmlRootElement
public class CourseTitle implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4264423995812179121L;
	private BigDecimal id;
	private String name;
	private String description;
	private String descUrl;

	public CourseTitle() {
	}

	public CourseTitle(BigDecimal id, String name, String description,
			String descUrl) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.descUrl = descUrl;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "NAME", nullable = false, length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "DESCRIPTION", length = 4000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "DESC_URL", length = 100)
	public String getDescUrl() {
		return this.descUrl;
	}

	public void setDescUrl(String descUrl) {
		this.descUrl = descUrl;
	}

}
