package gov.osha.dteAdmin;

// Generated Nov 21, 2012 11:24:52 AM by Hibernate Tools 4.0.0

import javax.persistence.*;
import javax.xml.bind.annotation.XmlRootElement;
import java.math.BigDecimal;

/**
 * DteUser generated by hbm2java
 */
@Entity
@Table(name = "DTE_USERS", schema = "DTE_COURSE_ADMIN", uniqueConstraints = @UniqueConstraint(columnNames = "OSHA_CN"))
@XmlRootElement
public class DteUser implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = -3875959503053404845L;
    private BigDecimal id;
    private EducationCenter educationCenter;
    private String extranetEmail;
    private String oshaCn;
    private String userType;
    private String updateUser;

    public DteUser() {
    }

    public DteUser(BigDecimal id, EducationCenter educationCenter,
                   String extranetEmail, String oshaCn, String userType, String updateUser) {
        setId(id);
        setEducationCenter(educationCenter);
        setExtranetEmail(extranetEmail);
        setOshaCn(oshaCn);
        setUserType(userType);
        setUpdateUser(updateUser);
    }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "G1")
    @SequenceGenerator(name = "G1", sequenceName = "user_seq", allocationSize = 1)
    @Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
    public BigDecimal getId() {
        return this.id;
    }

    public void setId(BigDecimal id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "CENTER_ID", nullable = false)
    public EducationCenter getEducationCenter() {
        return this.educationCenter;
    }

    public void setEducationCenter(EducationCenter educationCenter) {
        this.educationCenter = educationCenter;
    }

    @Column(name = "EXTRANET_EMAIL", nullable = false, length = 256)
    public String getExtranetEmail() {
        return this.extranetEmail;
    }

    public void setExtranetEmail(String extranetEmail) {
        this.extranetEmail = extranetEmail;
    }

    @Column(name = "OSHA_CN", unique = true, nullable = false, length = 100)
    public String getOshaCn() {
        return this.oshaCn;
    }

    public void setOshaCn(String oshaCn) {
        this.oshaCn = oshaCn;
    }

    @Column(name = "USER_TYPE", nullable = false, length = 1)
    public String getUserType() {
        return this.userType;
    }

    public void setUserType(String userType) {
        this.userType = userType;
    }

    @Column(name = "UPDATE_USER", length = 30)
    public String getUpdateUser() {
        return this.updateUser;
    }

    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }
}
