package gov.osha.dteAdmin;

// Generated Nov 21, 2012 11:24:52 AM by Hibernate Tools 4.0.0

import javax.persistence.*;
import javax.xml.bind.annotation.XmlRootElement;
import java.math.BigDecimal;

/**
 * EducationCenter generated by hbm2java
 */
@Entity
@Table(name = "OTI_EDUCATION_CENTERS", schema = "DTE_COURSE_ADMIN")
@XmlRootElement
public class EducationCenter implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 4879659815242778670L;
    private BigDecimal id;
    private StateCode stateCode;
    private String name;
    private String city;
    private String description;
    private String url;
    private String updateUser;

    public EducationCenter() {
    }

    public EducationCenter(BigDecimal id, StateCode stateCode,
                           String name, String updateUser) {
        setId(id);
        setStateCodes(stateCode);
        setName(name);
        setUpdateUser(updateUser);
    }

    public EducationCenter(BigDecimal id, StateCode stateCode,
                           String name, String city, String description, String url) {
        this.id = id;
        this.stateCode = stateCode;
        this.name = name;
        this.city = city;
        this.description = description;
        this.url = url;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "G1")
    @SequenceGenerator(name = "G1", sequenceName = "oti_ed_center_seq", allocationSize = 1)
    @Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
    public BigDecimal getId() {
        return this.id;
    }

    public void setId(BigDecimal id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "STATE_ID", nullable = false)
    public StateCode getStateCodes() {
        return this.stateCode;
    }

    public void setStateCodes(StateCode stateCode) {
        this.stateCode = stateCode;
    }

    @Column(name = "NAME", nullable = false, length = 100)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "CITY", length = 30)
    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    @Column(name = "DESCRIPTION", length = 250)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "URL", length = 200)
    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    @Column(name = "UPDATE_USER", length = 30)
    public String getUpdateUser() {
        return this.updateUser;
    }

    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

}
