package gov.osha.dteAdmin;

// Generated Nov 21, 2012 11:24:52 AM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * EducationCenter generated by hbm2java
 */
@Entity
@Table(name = "OTI_EDUCATION_CENTERS", schema = "DTE_COURSE_ADMIN")
@XmlRootElement
public class EducationCenter implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4879659815242778670L;
	private BigDecimal id;
	private StateCode stateCode;
	private String name;
	private String city;
	private String description;
	private String url;

	public EducationCenter() {
	}

	public EducationCenter(BigDecimal id, StateCode stateCode,
			String name) {
		this.id = id;
		this.stateCode = stateCode;
		this.name = name;
	}

	public EducationCenter(BigDecimal id, StateCode stateCode,
			String name, String city, String description, String url) {
		this.id = id;
		this.stateCode = stateCode;
		this.name = name;
		this.city = city;
		this.description = description;
		this.url = url;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "STATE_ID", nullable = false)
	public StateCode getOtiStateCodes() {
		return this.stateCode;
	}

	public void setOtiStateCodes(StateCode stateCode) {
		this.stateCode = stateCode;
	}

	@Column(name = "NAME", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "CITY", length = 30)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "DESCRIPTION", length = 250)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "URL", length = 200)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

}
