package gov.osha.dteAdmin;

// Generated Nov 21, 2012 11:24:52 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;
import java.math.BigDecimal;

/**
 * StateCode generated by hbm2java
 */
@Entity
@Table(name = "OTI_STATE_CODES", schema = "DTE_COURSE_ADMIN")
@XmlRootElement
public class StateCode implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4774642082196483662L;
	private BigDecimal id;
	private String stateCd;
	private String description;

	public StateCode() {
	}

	public StateCode(BigDecimal id, String stateCd, String description) {
		this.id = id;
		this.stateCd = stateCd;
		this.description = description;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "STATE_CD", nullable = false, length = 2)
	public String getStateCd() {
		return this.stateCd;
	}

	public void setStateCd(String stateCd) {
		this.stateCd = stateCd;
	}

	@Column(name = "DESCRIPTION", nullable = false, length = 30)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
